package bomberman.mechanics.interfaces;

public enum EntityType {
    BOMBERMAN, DESTRUCTIBLE_WALL, UNDESTRUCTIBLE_WALL, BONUS_INCMAXHP, BONUS_INCMAXRANGE, BONUS_DECBOMBSPAWN, BONUS_INCSPEED, BONUS_MOREBOMBS, BONUS_DROPBOMBONDEATH, BONUS_INVUL, BOMB, BOMB_RAY
}
